/**
 * (c) 2026 AI Studio - Dedicated FreeRTOS C++ Source Code Generator
 * Converts visual RTOS architecture (Tasks, Queues, Mutexes, Shared/Direct Variables, Timers, ISRs)
 * into high-performance, compilable FreeRTOS code for ESP32 (Xtensa Dual-Core SMP).
 */

import {
  RtosNode,
  RtosWire,
  RtosTaskData,
  RtosQueueData,
  RtosMutexData,
  RtosSharedVarData,
  RtosDirectVarData,
  RtosEventGroupData,
  RtosTimerData,
  RtosIsrData,
} from '../types';

export function generateFreeRtosCppCode(nodes: RtosNode[], wires: RtosWire[]): string {
  const taskNodes = nodes.filter((n) => n.type === 'task');
  const queueNodes = nodes.filter((n) => n.type === 'queue');
  const mutexNodes = nodes.filter((n) => n.type === 'mutex');
  const sharedVarNodes = nodes.filter((n) => n.type === 'shared_variable');
  const directVarNodes = nodes.filter((n) => n.type === 'direct_variable');
  const eventGroupNodes = nodes.filter((n) => n.type === 'event_group');
  const timerNodes = nodes.filter((n) => n.type === 'software_timer');
  const isrNodes = nodes.filter((n) => n.type === 'isr_handler');

  let code = `/**
 * ============================================================================
 *  ESP32 FreeRTOS Dual-Core Architecture (Generated by ArduASM Studio)
 *  Target MCU: ESP32-WROOM-32 @ 240 MHz (Xtensa LX6 Dual-Core SMP)
 *  FreeRTOS Version: 10.4.3 (ESP-IDF Kernel)
 * ============================================================================
 */

#include <Arduino.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include "freertos/event_groups.h"
#include "freertos/timers.h"

// ----------------------------------------------------------------------------
// 1. DATA STRUCTURES & PACKET TYPES
// ----------------------------------------------------------------------------
`;

  // Define sample message structures if queues exist
  if (queueNodes.length > 0) {
    queueNodes.forEach((q) => {
      const qData = q.data as RtosQueueData;
      if (qData.itemType.includes('_t') || qData.itemType.includes('Struct') || qData.itemType.includes('Packet')) {
        code += `
typedef struct {
  uint32_t timestamp;
  float value;
  uint8_t statusFlags;
  char source[16];
} ${qData.itemType};
`;
      }
    });
  }

  // 2. Shared Variables Declarations
  code += `
// ----------------------------------------------------------------------------
// 2. SHARED VARIABLES & ATOMIC BUFFERS
// ----------------------------------------------------------------------------
`;
  if (sharedVarNodes.length === 0) {
    code += `// (Nincsenek definiált globális megosztott változók)\n`;
  } else {
    sharedVarNodes.forEach((sv) => {
      const svData = sv.data as RtosSharedVarData;
      const initValStr = svData.initialValue !== undefined ? JSON.stringify(svData.initialValue) : '0';
      const isProtected = svData.protectedByMutexId != null;
      code += `volatile ${svData.dataType} g_${svData.name} = ${initValStr}; ${isProtected ? '// [VÉDETT]: Mutex zárolás kötelező!' : '// ⚠️ [FIGYELEM]: Védetlen megosztott változó!'}\n`;
    });
  }

  // 3. FreeRTOS Handles Declarations
  code += `
// ----------------------------------------------------------------------------
// 3. FREERTOS HANDLES (TASKS, QUEUES, MUTEXES, TIMERS, EVENT GROUPS)
// ----------------------------------------------------------------------------
`;

  // Task Handles
  taskNodes.forEach((t) => {
    const tData = t.data as RtosTaskData;
    code += `TaskHandle_t xHandle_${tData.name} = NULL;\n`;
  });

  // Queue Handles
  queueNodes.forEach((q) => {
    const qData = q.data as RtosQueueData;
    code += `QueueHandle_t xQueue_${qData.name} = NULL;\n`;
  });

  // Mutex Handles
  mutexNodes.forEach((m) => {
    const mData = m.data as RtosMutexData;
    code += `SemaphoreHandle_t xMutex_${mData.name} = NULL;\n`;
  });

  // Event Group Handles
  eventGroupNodes.forEach((eg) => {
    const egData = eg.data as RtosEventGroupData;
    code += `EventGroupHandle_t xEventGroup_${egData.name} = NULL;\n`;
  });

  // Timer Handles
  timerNodes.forEach((tm) => {
    const tmData = tm.data as RtosTimerData;
    code += `TimerHandle_t xTimer_${tmData.name} = NULL;\n`;
  });

  // 4. ISR Handlers
  if (isrNodes.length > 0) {
    code += `
// ----------------------------------------------------------------------------
// 4. HARDWARE INTERRUPT SERVICE ROUTINES (ISRs)
// ----------------------------------------------------------------------------
`;
    isrNodes.forEach((isr) => {
      const isrData = isr.data as RtosIsrData;
      code += `
void IRAM_ATTR isr_${isrData.name}() {
  BaseType_t xHigherPriorityTaskWoken = pdFALSE;

  // Hardver esemény feldolgozása megszakítási környezetben
`;
      // Find wires from ISR to queue or semaphore
      const isrWires = wires.filter((w) => w.fromNodeId === isr.id);
      isrWires.forEach((w) => {
        const targetNode = nodes.find((n) => n.id === w.toNodeId);
        if (targetNode?.type === 'queue') {
          const qData = targetNode.data as RtosQueueData;
          code += `  // Üzenet küldése a sorba ISR-ből
  ${qData.itemType} item;
  item.timestamp = millis();
  xQueueSendFromISR(xQueue_${qData.name}, &item, &xHigherPriorityTaskWoken);
`;
        } else if (targetNode?.type === 'mutex') {
          const mData = targetNode.data as RtosMutexData;
          code += `  // Szemafor felszabadítása ISR-ből
  xSemaphoreGiveFromISR(xMutex_${mData.name}, &xHigherPriorityTaskWoken);
`;
        } else if (targetNode?.type === 'task') {
          const tData = targetNode.data as RtosTaskData;
          code += `  // Közvetlen értesítés a taszknak ISR-ből
  vTaskNotifyGiveFromISR(xHandle_${tData.name}, &xHigherPriorityTaskWoken);
`;
        }
      });

      code += `
  if (xHigherPriorityTaskWoken == pdTRUE) {
    portYIELD_FROM_ISR();
  }
}
`;
    });
  }

  // 5. Software Timer Callbacks
  if (timerNodes.length > 0) {
    code += `
// ----------------------------------------------------------------------------
// 5. SOFTWARE TIMER CALLBACK FUNCTIONS
// ----------------------------------------------------------------------------
`;
    timerNodes.forEach((tm) => {
      const tmData = tm.data as RtosTimerData;
      code += `
void vTimerCallback_${tmData.name}(TimerHandle_t xTimer) {
  // Időzítő periódus lejárati callback hívás (${tmData.periodMs} ms)
  Serial.printf("[Timer %s] Tick event fired at %lu ms\\n", "${tmData.name}", millis());
}
`;
    });
  }

  // 6. FreeRTOS Task Worker Functions
  code += `
// ----------------------------------------------------------------------------
// 6. FREERTOS TASK WORKER ROUTINES (DUAL-CORE PARALLEL EXECUTION)
// ----------------------------------------------------------------------------
`;

  taskNodes.forEach((t) => {
    const tData = t.data as RtosTaskData;
    const coreName = tData.core === 0 ? 'Core 0 (PRO CPU)' : tData.core === 1 ? 'Core 1 (APP CPU)' : 'Bármelyik szabad mag';

    code += `
/**
 * @brief Taszk: ${tData.name}
 * @details Futási mag: ${coreName} | Prioritás: ${tData.priority} | Stack: ${tData.stackSize}B
 */
void vTask_${tData.name}(void *pvParameters) {
  (void)pvParameters;
  TickType_t xLastWakeTime = xTaskGetTickCount();
  const TickType_t xFrequency = pdMS_TO_TICKS(${tData.loopPeriodMs > 0 ? tData.loopPeriodMs : 10});

  Serial.printf("[Init] Taszk elindult: %s a %d. magon\\n", "${tData.name}", xPortGetCoreID());

  for (;;) {
`;

    // 6a. Check incoming direct notifications
    if (tData.notifyState !== 'NOT_WAITING') {
      code += `    // Közvetlen taszk értesítés fogadása (Zero-overhead IPC)
    uint32_t notifyValue = ulTaskNotifyTake(pdTRUE, pdMS_TO_TICKS(${tData.loopPeriodMs > 0 ? tData.loopPeriodMs : 100}));
    if (notifyValue > 0) {
      Serial.printf("[Task %s] Közvetlen értesítés fogadva: %u\\n", "${tData.name}", notifyValue);
    }
`;
    }

    // 6b. Check incoming queue wires (Consumers)
    const incomingQueueWires = wires.filter((w) => w.toNodeId === t.id && nodes.find((n) => n.id === w.fromNodeId)?.type === 'queue');
    incomingQueueWires.forEach((w) => {
      const qNode = nodes.find((n) => n.id === w.fromNodeId);
      if (qNode) {
        const qData = qNode.data as RtosQueueData;
        code += `    // Üzenet fogadása a(z) ${qData.name} sorból
    ${qData.itemType} rxItem;
    if (xQueueReceive(xQueue_${qData.name}, &rxItem, pdMS_TO_TICKS(${qData.receiveTimeoutMs || 50})) == pdPASS) {
      Serial.printf("[Task %s] Csomag érkezett a sorból! Időbélyeg: %lu\\n", "${tData.name}", rxItem.timestamp);
    }
`;
      }
    });

    // 6c. Check connected mutexes & shared variables
    const connectedMutexWires = wires.filter(
      (w) => (w.fromNodeId === t.id || w.toNodeId === t.id) && nodes.find((n) => n.id === (w.fromNodeId === t.id ? w.toNodeId : w.fromNodeId))?.type === 'mutex'
    );

    const connectedSharedVarWires = wires.filter(
      (w) => (w.fromNodeId === t.id || w.toNodeId === t.id) && nodes.find((n) => n.id === (w.fromNodeId === t.id ? w.toNodeId : w.fromNodeId))?.type === 'shared_variable'
    );

    if (connectedSharedVarWires.length > 0) {
      connectedSharedVarWires.forEach((w) => {
        const svNode = nodes.find((n) => n.id === (w.fromNodeId === t.id ? w.toNodeId : w.fromNodeId));
        if (svNode) {
          const svData = svNode.data as RtosSharedVarData;
          const associatedMutex = mutexNodes.find((m) => m.id === svData.protectedByMutexId);

          if (associatedMutex) {
            const mData = associatedMutex.data as RtosMutexData;
            code += `    // Megosztott változó biztonságos elérése Mutex védelemmel
    if (xSemaphoreTake(xMutex_${mData.name}, pdMS_TO_TICKS(100)) == pdTRUE) {
      // Kritikus szakasz (Critical Section)
      // g_${svData.name} = új érték;
      Serial.printf("[Task %s] g_%s értéke zárolva elérve\\n", "${tData.name}", "${svData.name}");
      xSemaphoreGive(xMutex_${mData.name}); // Zárolás feloldása
    } else {
      Serial.printf("[Task %s] Mutex zárolási időtúllépés!\\n", "${tData.name}");
    }
`;
          } else {
            code += `    // ⚠️ FIGYELEM: Védetlen közvetlen megosztott változó hozzáférés!
    // g_${svData.name} = érték;
`;
          }
        }
      });
    }

    // 6d. Check outgoing queue wires (Producers)
    const outgoingQueueWires = wires.filter((w) => w.fromNodeId === t.id && nodes.find((n) => n.id === w.toNodeId)?.type === 'queue');
    outgoingQueueWires.forEach((w) => {
      const qNode = nodes.find((n) => n.id === w.toNodeId);
      if (qNode) {
        const qData = qNode.data as RtosQueueData;
        code += `    // Új mérési adat küldése a(z) ${qData.name} sorba
    ${qData.itemType} txItem;
    txItem.timestamp = millis();
    txItem.value = random(100, 500) / 10.0f;
    if (xQueueSend(xQueue_${qData.name}, &txItem, pdMS_TO_TICKS(${qData.sendTimeoutMs || 20})) != pdPASS) {
      Serial.printf("[Task %s] Sor megtelt! Üzenet eldobva\\n", "${tData.name}");
    }
`;
      }
    });

    // 6e. Yield / Delay
    if (tData.hasYield && tData.loopPeriodMs > 0) {
      code += `
    // Időzített feladatütemezés átadása (Preemptive FreeRTOS Tick)
    vTaskDelayUntil(&xLastWakeTime, xFrequency);
`;
    } else {
      code += `
    // Minimális átadás az Idle taszk és Watchdog számára
    vTaskDelay(pdMS_TO_TICKS(10));
`;
    }

    code += `  }
  vTaskDelete(NULL);
}
`;
  });

  // 7. SETUP FUNCTION
  code += `
// ----------------------------------------------------------------------------
// 7. SYSTEM INITIALIZATION & RTOS SCHEDULER BOOTSTRAP (setup())
// ----------------------------------------------------------------------------
void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println("\\n=======================================================");
  Serial.println("  ESP32 FreeRTOS Dual-Core Rendszer Indítása...       ");
  Serial.println("=======================================================");
`;

  // Create Mutexes
  if (mutexNodes.length > 0) {
    code += `\n  // 1. Mutexek és Szemaforok Inicializálása\n`;
    mutexNodes.forEach((m) => {
      const mData = m.data as RtosMutexData;
      if (mData.type === 'recursive_mutex') {
        code += `  xMutex_${mData.name} = xSemaphoreCreateRecursiveMutex();\n`;
      } else if (mData.type === 'binary_semaphore') {
        code += `  xMutex_${mData.name} = xSemaphoreCreateBinary();\n  xSemaphoreGive(xMutex_${mData.name});\n`;
      } else if (mData.type === 'counting_semaphore') {
        code += `  xMutex_${mData.name} = xSemaphoreCreateCounting(${mData.maxCount || 10}, ${mData.currentCount || 0});\n`;
      } else {
        code += `  xMutex_${mData.name} = xSemaphoreCreateMutex(); // Beépített prioritás-öröklődés\\n`;
      }
    });
  }

  // Create Queues
  if (queueNodes.length > 0) {
    code += `\n  // 2. Üzenetsorok (FreeRTOS Queues) Létrehozása\n`;
    queueNodes.forEach((q) => {
      const qData = q.data as RtosQueueData;
      code += `  xQueue_${qData.name} = xQueueCreate(${qData.length}, sizeof(${qData.itemType}));\n`;
      code += `  if (xQueue_${qData.name} == NULL) {\n    Serial.println("Hiba: ${qData.name} sor nem hozható létre (nincs elég heap mem)!\\n");\n  }\n`;
    });
  }

  // Create Event Groups
  if (eventGroupNodes.length > 0) {
    code += `\n  // 3. Eseménycsoportok (Event Groups) Inicializálása\n`;
    eventGroupNodes.forEach((eg) => {
      const egData = eg.data as RtosEventGroupData;
      code += `  xEventGroup_${egData.name} = xEventGroupCreate();\n`;
    });
  }

  // Create Software Timers
  if (timerNodes.length > 0) {
    code += `\n  // 4. Szoftveres Időzítők (Software Timers) Indítása\n`;
    timerNodes.forEach((tm) => {
      const tmData = tm.data as RtosTimerData;
      code += `  xTimer_${tmData.name} = xTimerCreate(\n    "${tmData.name}",\n    pdMS_TO_TICKS(${tmData.periodMs}),\n    ${tmData.autoReload ? 'pdTRUE' : 'pdFALSE'},\n    (void*)0,\n    vTimerCallback_${tmData.name}\n  );\n`;
      code += `  xTimerStart(xTimer_${tmData.name}, 0);\n`;
    });
  }

  // Create Tasks Pinned to Core
  code += `\n  // 5. Párhuzamos Taszkok Létrehozása és Hozzárendelése a Magokhoz\n`;
  taskNodes.forEach((t) => {
    const tData = t.data as RtosTaskData;
    const coreParam = tData.core === 0 ? '0' : tData.core === 1 ? '1' : 'tskNO_AFFINITY';
    code += `  xTaskCreatePinnedToCore(\n    vTask_${tData.name},      /* Taszk függvény */\n    "${tData.name}",          /* Név leíró */\n    ${tData.stackSize},       /* Stack méret byte-ban */\n    NULL,                     /* Paraméterek */\n    ${tData.priority},        /* Prioritás (0-24) */\n    &xHandle_${tData.name},   /* Taszk Handle */\n    ${coreParam}              /* Core ID: 0 (PRO CPU) vagy 1 (APP CPU) */\n  );\n\n`;
  });

  code += `  Serial.printf("FreeRTOS Rendszer sikeresen elindult! Szabad Heap: %d byte\\n", esp_get_free_heap_size());
}

// ----------------------------------------------------------------------------
// 8. ARDUINO MAIN LOOP (Fut a Core 1 magon Idle prioritással)
// ----------------------------------------------------------------------------
void loop() {
  // A FreeRTOS párhuzamos taszkjai futnak a háttérben.
  // A loop() itt alacsony terhelést végezhet.
  vTaskDelay(pdMS_TO_TICKS(1000));
}
`;

  return code;
}
